version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run: curl -O  https://jita.eng.nutanix.com/api/v2/job_profiles/5e411ae42bc0c47a67b5cd42/trigger
